"""initial relational schema

Revision ID: 20fb0c814e83
Revises: 
Create Date: 2026-09-13 00:16:30.669881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy          # autogenerate renders pgvector types without importing them
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20fb0c814e83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), server_default='', nullable=False),
    sa.Column('icon', sa.String(length=40), server_default='', nullable=False),
    sa.Column('model', sa.String(length=120), server_default='', nullable=False),
    sa.Column('fallback_model', sa.String(length=120), server_default='', nullable=False),
    sa.Column('status', sa.Enum('running', 'idle', 'waiting', 'blocked', 'error', 'disabled', name='agent_status'), server_default='idle', nullable=False),
    sa.Column('autonomy', sa.Enum('supervised', 'semi', 'autonomous', name='autonomy'), server_default='supervised', nullable=False),
    sa.Column('system_prompt', sa.Text(), server_default='', nullable=False),
    sa.Column('tasks_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success_rate', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('guardrails', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_table('mcp_servers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('transport', sa.Enum('stdio', 'http', 'sse', name='mcp_transport'), server_default='stdio', nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', 'error', 'auth_required', name='mcp_status'), server_default='disconnected', nullable=False),
    sa.Column('scope', sa.Enum('global', 'project', 'local', name='scope'), server_default='global', nullable=False),
    sa.Column('command', sa.Text(), server_default='', nullable=False),
    sa.Column('resources', sa.Integer(), server_default='0', nullable=False),
    sa.Column('prompts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('calls_24h', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('untrusted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('default_effect', sa.String(length=20), server_default='ask', nullable=False),
    sa.Column('config', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_servers'))
    )
    op.create_table('memory_conflicts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='conflict_status'), server_default='open', nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='MEDIUM', nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('suggestion', sa.Text(), server_default='', nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('a', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('b', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_conflicts'))
    )
    op.create_table('permission_rules',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('tool', sa.String(length=120), server_default='', nullable=False),
    sa.Column('effect', sa.String(length=20), server_default='ask', nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk'), server_default='LOW', nullable=False),
    sa.Column('scope', sa.Enum('global', 'project', 'local', name='scope'), server_default='global', nullable=False),
    sa.Column('hits_24h', sa.Integer(), server_default='0', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_rules'))
    )
    op.create_table('prefs',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prefs'))
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('codename', sa.String(length=80), server_default='', nullable=False),
    sa.Column('kind', sa.Enum('legacy', 'greenfield', 'platform', name='project_kind'), server_default='platform', nullable=False),
    sa.Column('status', sa.Enum('active', 'onboarding', 'paused', 'archived', name='project_status'), server_default='active', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('repo', sa.Text(), server_default='', nullable=False),
    sa.Column('lines_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('files_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('modules', sa.Integer(), server_default='0', nullable=False),
    sa.Column('db_tables', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stored_procs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('memory_pct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('understood_pct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_kind', sa.Enum('git', 'local', name='source_kind'), nullable=True),
    sa.Column('source_repo', sa.Text(), server_default='', nullable=False),
    sa.Column('source_branch', sa.String(length=200), server_default='', nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('excluded', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('stack', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('builtin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='user_status'), server_default='active', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_workspace_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace'))
    )
    op.create_table('activity',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('actor_kind', sa.Enum('human', 'agent', 'system', 'hook', 'tool', name='actor_kind'), server_default='system', nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('level', sa.Enum('info', 'ok', 'warn', 'err', name='level'), server_default='info', nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('task_ref', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_activity_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_activity'))
    )
    op.create_index(op.f('ix_activity_at'), 'activity', ['at'], unique=False)
    op.create_index('ix_activity_project_id_at', 'activity', ['project_id', 'at'], unique=False)
    op.create_table('ai_calls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feature', sa.String(length=40), nullable=False),
    sa.Column('lane', sa.String(length=40), server_default='', nullable=False),
    sa.Column('model', sa.String(length=120), server_default='', nullable=False),
    sa.Column('ok', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ai_calls_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_calls_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_calls'))
    )
    op.create_index(op.f('ix_ai_calls_at'), 'ai_calls', ['at'], unique=False)
    op.create_index('ix_ai_calls_feature_at', 'ai_calls', ['feature', 'at'], unique=False)
    op.create_index('ix_ai_calls_lane_at', 'ai_calls', ['lane', 'at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('agent', sa.String(length=120), server_default='', nullable=False),
    sa.Column('tool', sa.String(length=120), server_default='', nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk'), server_default='LOW', nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', name='approval_status'), server_default='pending', nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.Text(), server_default='', nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('run_ref', sa.String(length=40), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_approvals_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_approvals_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('ref', name=op.f('uq_approvals_ref'))
    )
    op.create_index('ix_approvals_status_created_at', 'approvals', ['status', 'created_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target', sa.Text(), server_default='', nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip', sa.String(length=64), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_action_at', 'audit_log', ['action', 'at'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('brainstorms',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('idea', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='complete', nullable=False),
    sa.Column('verdict', sa.Text(), server_default='', nullable=False),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('requested_by', sa.String(length=120), server_default='', nullable=False),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('devils_advocate', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('mvp', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('roadmap', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('compiler', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_brainstorms_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brainstorms')),
    sa.UniqueConstraint('ref', name=op.f('uq_brainstorms_ref'))
    )
    op.create_table('chats',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.Enum('idle', 'thinking', name='chat_status'), server_default='idle', nullable=False),
    sa.Column('started_by', sa.String(length=120), server_default='', nullable=False),
    sa.Column('last_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('turns', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tool_calls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('lane', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_chats_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats')),
    sa.UniqueConstraint('ref', name=op.f('uq_chats_ref'))
    )
    op.create_index('ix_chats_project_id_last_at', 'chats', ['project_id', 'last_at'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.Enum('code', 'doc', 'memory', name='chunk_kind'), nullable=False),
    sa.Column('ref', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), server_default='', nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('line', sa.Integer(), server_default='0', nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('dim', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model', sa.String(length=120), server_default='', nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', title || ' ' || body)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_chunks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('project_id', 'kind', 'ref', name=op.f('uq_chunks_project_id_kind_ref'))
    )
    op.create_index('ix_chunks_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_project_id_kind', 'chunks', ['project_id', 'kind'], unique=False)
    op.create_index('ix_chunks_search', 'chunks', ['search'], unique=False, postgresql_using='gin')
    op.create_table('code_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=40), server_default='', nullable=False),
    sa.Column('module', sa.String(length=200), server_default='', nullable=False),
    sa.Column('lines', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sha1', sa.String(length=40), server_default='', nullable=False),
    sa.Column('complexity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('churn', sa.Integer(), server_default='0', nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_code_files_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_files')),
    sa.UniqueConstraint('project_id', 'path', name=op.f('uq_code_files_project_id_path'))
    )
    op.create_index('ix_code_files_path_trgm', 'code_files', ['path'], unique=False, postgresql_using='gin', postgresql_ops={'path': 'gin_trgm_ops'})
    op.create_index('ix_code_files_project_id_module', 'code_files', ['project_id', 'module'], unique=False)
    op.create_table('code_index_runs',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('root', sa.Text(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('symbols', sa.Integer(), server_default='0', nullable=False),
    sa.Column('edges', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unresolved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parsers', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_code_index_runs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_code_index_runs'))
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('verdict', sa.String(length=60), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('by_user_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['by_user_id'], ['users.id'], name=op.f('fk_decisions_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_decisions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_table('mcp_tools',
    sa.Column('server_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk'), server_default='LOW', nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], name=op.f('fk_mcp_tools_server_id_mcp_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'name', name=op.f('pk_mcp_tools'))
    )
    op.create_table('memory_facts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('category', sa.Enum('human', 'project', 'architecture', 'business_rules', 'legacy', 'database', 'bugs', 'decisions', 'incidents', 'preferences', 'code', name='memory_category'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('source', sa.Text(), server_default='', nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidence'), server_default='MEDIUM', nullable=False),
    sa.Column('strength', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', title || ' ' || body || ' ' || reason)", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_memory_facts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_facts')),
    sa.UniqueConstraint('ref', name=op.f('uq_memory_facts_ref'))
    )
    op.create_index('ix_memory_facts_project_id_category', 'memory_facts', ['project_id', 'category'], unique=False)
    op.create_index('ix_memory_facts_search', 'memory_facts', ['search'], unique=False, postgresql_using='gin')
    op.create_table('retrieval_runs',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('embedded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model', sa.String(length=120), server_default='', nullable=False),
    sa.Column('lane', sa.String(length=40), server_default='', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_retrieval_runs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_retrieval_runs'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.Column('permission', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission', name=op.f('pk_role_permissions'))
    )
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_user_id_expires_at', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('backlog', 'planning', 'in_progress', 'review', 'blocked', 'done', name='task_status'), server_default='backlog', nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='priority'), server_default='NORMAL', nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk'), server_default='LOW', nullable=False),
    sa.Column('epic', sa.String(length=120), server_default='', nullable=False),
    sa.Column('requirement', sa.Text(), server_default='', nullable=False),
    sa.Column('worktree', sa.Text(), server_default='', nullable=False),
    sa.Column('blocked_reason', sa.Text(), server_default='', nullable=False),
    sa.Column('files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('layers', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('ref', name=op.f('uq_tasks_ref'))
    )
    op.create_index('ix_tasks_project_id_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id', name=op.f('pk_team_members'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=40), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.Enum('you', 'assistant', 'tool', 'note', name='chat_role'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('by', sa.String(length=120), server_default='', nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('lane', sa.String(length=40), nullable=True),
    sa.Column('ms', sa.Integer(), nullable=True),
    sa.Column('tool', sa.String(length=60), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('why', sa.Text(), server_default='', nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_chat_messages_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_chat_id_id', 'chat_messages', ['chat_id', 'id'], unique=False)
    op.create_table('code_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('from_file', sa.BigInteger(), nullable=False),
    sa.Column('to_file', sa.BigInteger(), nullable=True),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('imports', 'uses', 'reads', 'writes', 'calls', name='edge_kind'), nullable=False),
    sa.ForeignKeyConstraint(['from_file'], ['code_files.id'], name=op.f('fk_code_edges_from_file_code_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_code_edges_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_file'], ['code_files.id'], name=op.f('fk_code_edges_to_file_code_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_edges'))
    )
    op.create_index(op.f('ix_code_edges_from_file'), 'code_edges', ['from_file'], unique=False)
    op.create_index('ix_code_edges_project_id_target', 'code_edges', ['project_id', 'target'], unique=False)
    op.create_index('ix_code_edges_to_file_kind', 'code_edges', ['to_file', 'kind'], unique=False)
    op.create_table('code_symbols',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), server_default='', nullable=False),
    sa.Column('line', sa.Integer(), server_default='0', nullable=False),
    sa.Column('exported', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', regexp_replace(regexp_replace(name, '([a-z0-9])([A-Z])', '\\1 \\2', 'g'), '[_.-]', ' ', 'g'))", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['code_files.id'], name=op.f('fk_code_symbols_file_id_code_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_code_symbols_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_symbols'))
    )
    op.create_index(op.f('ix_code_symbols_file_id'), 'code_symbols', ['file_id'], unique=False)
    op.create_index('ix_code_symbols_name_trgm', 'code_symbols', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_code_symbols_project_id_name', 'code_symbols', ['project_id', 'name'], unique=False)
    op.create_index('ix_code_symbols_search', 'code_symbols', ['search'], unique=False, postgresql_using='gin')
    op.create_table('memory_tags',
    sa.Column('fact_id', sa.String(length=40), nullable=False),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['memory_facts.id'], name=op.f('fk_memory_tags_fact_id_memory_facts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id', 'tag', name=op.f('pk_memory_tags'))
    )
    op.create_index(op.f('ix_memory_tags_tag'), 'memory_tags', ['tag'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('draft', 'dispatched', name='plan_status'), server_default='draft', nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk'), server_default='LOW', nullable=False),
    sa.Column('confidence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('raw_requirement', sa.Text(), server_default='', nullable=False),
    sa.Column('business_requirement', sa.Text(), server_default='', nullable=False),
    sa.Column('technical_requirement', sa.Text(), server_default='', nullable=False),
    sa.Column('architecture_impact', sa.Text(), server_default='', nullable=False),
    sa.Column('requested_by', sa.String(length=120), server_default='', nullable=False),
    sa.Column('affected_modules', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('affected_files', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('affected_db', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('test_plan', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('cited', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('compiler', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_plans_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_plans_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('ref', name=op.f('uq_plans_ref'))
    )
    op.create_index('ix_plans_project_id_created_at', 'plans', ['project_id', 'created_at'], unique=False)
    op.create_table('task_agents',
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('agent', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_agents_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'agent', name=op.f('pk_task_agents'))
    )
    op.create_table('task_checklist',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('done', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_checklist_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_checklist')),
    sa.UniqueConstraint('task_id', 'n', name=op.f('uq_task_checklist_task_id_n'))
    )
    op.create_table('plan_questions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), server_default='', nullable=False),
    sa.Column('deferred', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_questions_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_questions')),
    sa.UniqueConstraint('plan_id', 'n', name=op.f('uq_plan_questions_plan_id_n'))
    )
    op.create_table('plan_steps',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('agent', sa.String(length=120), server_default='', nullable=False),
    sa.Column('state', sa.Enum('done', 'active', 'todo', 'failed', 'skipped', name='step_state'), server_default='todo', nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_steps_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_steps')),
    sa.UniqueConstraint('plan_id', 'n', name=op.f('uq_plan_steps_plan_id_n'))
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('plan_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'waiting', 'done', 'failed', 'cancelled', name='run_status'), server_default='queued', nullable=False),
    sa.Column('role', sa.Enum('solo', 'agent', 'integration', name='run_role'), server_default='solo', nullable=False),
    sa.Column('agent', sa.String(length=120), nullable=True),
    sa.Column('lane', sa.String(length=40), nullable=True),
    sa.Column('parent_id', sa.String(length=40), nullable=True),
    sa.Column('branch', sa.Text(), nullable=False),
    sa.Column('worktree', sa.Text(), nullable=False),
    sa.Column('repo', sa.Text(), nullable=False),
    sa.Column('prefix', sa.Text(), server_default='', nullable=False),
    sa.Column('base', sa.String(length=64), server_default='', nullable=False),
    sa.Column('requirement', sa.Text(), server_default='', nullable=False),
    sa.Column('requested_by', sa.String(length=120), server_default='', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('removed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('waiting_on', sa.String(length=40), nullable=True),
    sa.Column('diff_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('diff_insertions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('diff_deletions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('diff_commits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tests_command', sa.Text(), server_default='', nullable=False),
    sa.Column('tests_status', sa.String(length=20), server_default='not run', nullable=False),
    sa.Column('tests_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('review', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('merged', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('targets', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['runs.id'], name=op.f('fk_runs_parent_id_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_runs_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_runs_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    sa.UniqueConstraint('ref', name=op.f('uq_runs_ref'))
    )
    op.create_index(op.f('ix_runs_parent_id'), 'runs', ['parent_id'], unique=False)
    op.create_index('ix_runs_project_id_created_at', 'runs', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_runs_status_created_at', 'runs', ['status', 'created_at'], unique=False)
    op.create_table('run_conflicts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('branch', sa.Text(), nullable=False),
    sa.Column('agent', sa.String(length=120), server_default='', nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_conflicts_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_conflicts'))
    )
    op.create_index(op.f('ix_run_conflicts_run_id'), 'run_conflicts', ['run_id'], unique=False)
    op.create_table('run_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('info', 'ok', 'warn', 'err', name='level'), server_default='info', nullable=False),
    sa.Column('line', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_logs_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_logs'))
    )
    op.create_index('ix_run_logs_run_id_id', 'run_logs', ['run_id', 'id'], unique=False)
    op.create_table('run_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('edit', 'merge', 'test', 'review', 'handoff', name='run_step_kind'), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('agent', sa.String(length=120), server_default='', nullable=False),
    sa.Column('status', sa.Enum('todo', 'running', 'waiting', 'done', 'failed', 'skipped', name='run_step_status'), server_default='todo', nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('ms', sa.Integer(), nullable=True),
    sa.Column('child_run_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['child_run_id'], ['runs.id'], name=op.f('fk_run_steps_child_run_id_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_steps_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_steps')),
    sa.UniqueConstraint('run_id', 'n', name=op.f('uq_run_steps_run_id_n'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_steps')
    op.drop_index('ix_run_logs_run_id_id', table_name='run_logs')
    op.drop_table('run_logs')
    op.drop_index(op.f('ix_run_conflicts_run_id'), table_name='run_conflicts')
    op.drop_table('run_conflicts')
    op.drop_index('ix_runs_status_created_at', table_name='runs')
    op.drop_index('ix_runs_project_id_created_at', table_name='runs')
    op.drop_index(op.f('ix_runs_parent_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('plan_steps')
    op.drop_table('plan_questions')
    op.drop_table('task_checklist')
    op.drop_table('task_agents')
    op.drop_index('ix_plans_project_id_created_at', table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_memory_tags_tag'), table_name='memory_tags')
    op.drop_table('memory_tags')
    op.drop_index('ix_code_symbols_search', table_name='code_symbols', postgresql_using='gin')
    op.drop_index('ix_code_symbols_project_id_name', table_name='code_symbols')
    op.drop_index('ix_code_symbols_name_trgm', table_name='code_symbols', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_code_symbols_file_id'), table_name='code_symbols')
    op.drop_table('code_symbols')
    op.drop_index('ix_code_edges_to_file_kind', table_name='code_edges')
    op.drop_index('ix_code_edges_project_id_target', table_name='code_edges')
    op.drop_index(op.f('ix_code_edges_from_file'), table_name='code_edges')
    op.drop_table('code_edges')
    op.drop_index('ix_chat_messages_chat_id_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('user_roles')
    op.drop_table('team_members')
    op.drop_index('ix_tasks_project_id_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_sessions_user_id_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('role_permissions')
    op.drop_table('retrieval_runs')
    op.drop_index('ix_memory_facts_search', table_name='memory_facts', postgresql_using='gin')
    op.drop_index('ix_memory_facts_project_id_category', table_name='memory_facts')
    op.drop_table('memory_facts')
    op.drop_table('mcp_tools')
    op.drop_table('decisions')
    op.drop_table('code_index_runs')
    op.drop_index('ix_code_files_project_id_module', table_name='code_files')
    op.drop_index('ix_code_files_path_trgm', table_name='code_files', postgresql_using='gin', postgresql_ops={'path': 'gin_trgm_ops'})
    op.drop_table('code_files')
    op.drop_index('ix_chunks_search', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_project_id_kind', table_name='chunks')
    op.drop_index('ix_chunks_embedding', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('chunks')
    op.drop_index('ix_chats_project_id_last_at', table_name='chats')
    op.drop_table('chats')
    op.drop_table('brainstorms')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index('ix_audit_log_action_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_approvals_status_created_at', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_ai_calls_lane_at', table_name='ai_calls')
    op.drop_index('ix_ai_calls_feature_at', table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_at'), table_name='ai_calls')
    op.drop_table('ai_calls')
    op.drop_index('ix_activity_project_id_at', table_name='activity')
    op.drop_index(op.f('ix_activity_at'), table_name='activity')
    op.drop_table('activity')
    op.drop_table('workspace')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('settings')
    op.drop_table('roles')
    op.drop_table('projects')
    op.drop_table('prefs')
    op.drop_table('permission_rules')
    op.drop_table('memory_conflicts')
    op.drop_table('mcp_servers')
    op.drop_table('agents')
    # ### end Alembic commands ###
