"""the ledger outlives its project

Revision ID: 70aaad7321c6
Revises: 7e41c0a9b2d5
Create Date: 2026-09-16 20:07:15.277683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy          # autogenerate renders pgvector types without importing them


# revision identifiers, used by Alembic.
revision: str = '70aaad7321c6'
down_revision: Union[str, Sequence[str], None] = '7e41c0a9b2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ai_calls_project_id_projects'), 'ai_calls', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ai_calls_project_id_projects'), 'ai_calls', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ai_calls_project_id_projects'), 'ai_calls', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ai_calls_project_id_projects'), 'ai_calls', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
