"""retrieval reads code names, a workflow step is a node, a run step counts its tries

Three things, each measured before it was written:

- `chunks.search` is rebuilt so the lexical half of retrieval can find a name a programmer would type.
  Postgres reads `GateActions` as one lexeme and `app/services/retrieval.py` as another, so "gate actions"
  matched nothing in the whole TypeScript front end and "services retrieval" matched nothing at all — and
  that is exactly the half that answers when no lane can embed. The title and path are added a second time,
  split at case changes and at a path's separators, with immutable functions only, so the column stays
  generated and cannot drift from its row.
- A workflow step gains `after`, `when`, `retry` and `calls`: the four things that turn an ordered list into
  a graph with waves, conditions, a retry policy and sub-workflows. Every one defaults to the list it is
  today, so every workflow that exists keeps running exactly as it ran.
- A run step counts its attempts, so a step tried again after a failure stays the same step.


Revision ID: 95bad98c334e
Revises: a17f3c92d4be
Create Date: 2026-09-20

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy          # autogenerate renders pgvector types without importing them
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95bad98c334e'
down_revision: Union[str, Sequence[str], None] = 'a17f3c92d4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_steps', sa.Column('attempts', sa.Integer(), server_default='1', nullable=False))
    op.add_column('run_steps', sa.Column('max_attempts', sa.Integer(), server_default='1', nullable=False))
    op.add_column('workflow_steps', sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('workflow_steps', sa.Column('when', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('workflow_steps', sa.Column('retry', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('workflow_steps', sa.Column('calls', sa.String(length=40), nullable=True))
    op.create_foreign_key(op.f('fk_workflow_steps_calls_workflow_definitions'), 'workflow_steps', 'workflow_definitions', ['calls'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint("agent_or_calls", "workflow_steps", "(calls IS NULL) <> (agent = '')")

    # The generated column is replaced, not altered: Postgres has no ALTER for a generation expression.
    op.drop_index("ix_chunks_search", table_name="chunks")
    op.drop_column("chunks", "search")
    op.add_column("chunks", sa.Column(
        "search", postgresql.TSVECTOR(),
        sa.Computed("to_tsvector('english', title || ' ' || body || ' ' || "
                    "translate(regexp_replace(title || ' ' || path, '([a-z0-9])([A-Z])', '\\1 \\2', 'g'), "
                    "'/._-:', '     '))", persisted=True),
        nullable=True))
    op.create_index("ix_chunks_search", "chunks", ["search"], postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chunks_search", table_name="chunks")
    op.drop_column("chunks", "search")
    op.add_column("chunks", sa.Column(
        "search", postgresql.TSVECTOR(),
        sa.Computed("to_tsvector('english', title || ' ' || body)", persisted=True), nullable=True))
    op.create_index("ix_chunks_search", "chunks", ["search"], postgresql_using="gin")
    # The naming convention adds the ck_<table>_ prefix, so the bare name is what goes in.
    op.drop_constraint("agent_or_calls", "workflow_steps", type_="check")
    op.drop_constraint(op.f('fk_workflow_steps_calls_workflow_definitions'), 'workflow_steps', type_='foreignkey')
    op.drop_column('workflow_steps', 'calls')
    op.drop_column('workflow_steps', 'retry')
    op.drop_column('workflow_steps', 'when')
    op.drop_column('workflow_steps', 'after')
    op.drop_column('run_steps', 'max_attempts')
    op.drop_column('run_steps', 'attempts')
    # ### end Alembic commands ###
