"""the ledger records which agent asked

Revision ID: b589e3c9d161
Revises: 0d132a2d78a9
Create Date: 2026-09-15 22:22:20.205123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy          # autogenerate renders pgvector types without importing them


# revision identifiers, used by Alembic.
revision: str = 'b589e3c9d161'
down_revision: Union[str, Sequence[str], None] = '0d132a2d78a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_calls', sa.Column('agent', sa.String(length=60), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_calls', 'agent')
    # ### end Alembic commands ###
