"""login attempts

Revision ID: ba71ca7751e2
Revises: 20fb0c814e83
Create Date: 2026-09-13 00:31:13.788951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy          # autogenerate renders pgvector types without importing them
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba71ca7751e2'
down_revision: Union[str, Sequence[str], None] = '20fb0c814e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ok', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ip', sa.String(length=64), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempts_email_at', 'login_attempts', ['email', 'at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempts_email_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
