"""Memory: the facts, and the conflicts between them.

Search is the part worth reading. It used to be an FTS5 shadow table that had to be written in step
with every change. Here the `search` column is generated by the database from the fact's own words,
so it cannot fall behind — and ranking is `ts_rank` with pinned facts first, in one statement.
"""
from __future__ import annotations

from sqlalchemy import ColumnElement, Integer, cast, func, select

from ..models import MemoryConflict, MemoryFact
from .base import Page, Repository
from .words import Mode, tsquery


class MemoryRepository(Repository[MemoryFact]):
    model = MemoryFact

    async def by_ref(self, ref: str) -> MemoryFact | None:
        return await self.one(MemoryFact.ref == ref)

    async def search(self, q: str = "", *, category: str | None = None, project: str | None = None,
                     include_archived: bool = False, limit: int | None = None,
                     mode: Mode = "all") -> list[MemoryFact]:
        """Words if there are any, otherwise everything that matches the filters — pinned first.

        `mode` is the difference between a search box and a question. Someone typing into the box
        means every word ("all"); someone asking "where does invoice rounding happen, and why there?"
        does not, and requiring all of it returns nothing at all. Ask memory passes "any".
        """
        where: list[ColumnElement[bool]] = []
        if not include_archived:
            where.append(MemoryFact.archived.is_(False))
        if category:
            where.append(MemoryFact.category == category)
        if project and project != "global":
            where.append(MemoryFact.project_id == project)
        elif project == "global":
            where.append(MemoryFact.project_id.is_(None))

        stmt = select(MemoryFact).where(*where)
        if q.strip():
            query = tsquery(q, mode)
            stmt = stmt.where(MemoryFact.search.op("@@")(query)).order_by(
                MemoryFact.pinned.desc(), func.ts_rank(MemoryFact.search, query).desc())
        else:
            stmt = stmt.order_by(MemoryFact.pinned.desc(), MemoryFact.strength.desc())
        stmt = stmt.limit(min(limit or 200, 500))
        return list((await self.session.execute(stmt)).scalars().unique())

    async def next_ref(self, prefix: str = "MEM-") -> str:
        return await super().next_ref(MemoryFact.ref, prefix)

    async def archive(self, fact: MemoryFact) -> MemoryFact:
        """Archived, never deleted: a fact that was wrong is still evidence of what was believed."""
        fact.archived = True
        await self.session.flush()
        return fact


class ConflictRepository(Repository[MemoryConflict]):
    model = MemoryConflict

    async def open(self, *, limit: int | None = None, offset: int = 0) -> Page[MemoryConflict]:
        return await self.page(MemoryConflict.status == "open", order_by=MemoryConflict.detected_at,
                               limit=limit, offset=offset)
